### ISSUE TITLE
"not a git repo" error

### ISSUE THREAD

**Issue by Berkmann18** [dtinth/todo-actions#45]
After trying to get this action to work on a private **repo**, I get this rather interesting error:
```
{"time":"2019-12-23T17:49:43.992Z","hostname":"860f8ffc12ff","pid":7,"level":"debug","name":"CodeRepository","message":"Found GitHub Action event file"}
{"time":"2019-12-23T17:49:44.106Z","hostname":"860f8ffc12ff","pid":7,"level":"info","name":"main","message":"Search for files with TODO tags..."}
{"time":"2019-12-23T17:49:44.107Z","hostname":"860f8ffc12ff","pid":7,"level":"info","name":"CodeRepository","message":"Search for files with TODO tags..."}
fatal: Not a git repository (or any parent up to mount point /github/workspace)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
CLIEntrypoint.js

Collect TODOs and create issues

Options:
  --version  Show version number                                       [boolean]
  --help     Show help                                                 [boolean]

Error: Command failed: git grep -Il TODO
fatal: Not a git repository (or any parent up to mount point /github/workspace)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

    at checkExecSyncError (child_process.js:623:11)
    at Object.execSync (child_process.js:659:15)
    at Object.<anonymous> (/app/lib/CodeRepository.js:37:53)
    at Generator.next (<anonymous>)
    at /app/lib/CodeRepository.js:7:71
```

The action is located in `.github/workflows/todo.yml`.

**Comment by milewski** [comment]
Same issue, any idea? @Berkmann18

**Comment by Berkmann18** [comment]
@milewski Nope, I've not tried using it since.
